version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MONGODB_HOST
      - MONGODB_USERNAME
      - MONGODB_PASSWORD
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - "27017:27017"